FROM openjdk:8-jre-alpine
#RUN apk add --no-cache openjdk8
#COPY files/UnlimitedJCEPolicyJDK8/* \ /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/
EXPOSE 8080
ADD /target/com-contract-service-0.0.1-SNAPSHOT.jar  com-contract-service.jar
RUN chmod 777 com-contract-service.jar
ENTRYPOINT ["java" , " -jar " , "	com-contract-service.jar "]